import './globals.css'
import { Inter, Poppins, Pridi } from 'next/font/google'

import Provider from '../components/QueryProvider'

const inter = Inter({ subsets: ['latin'] })
// const poppins = Poppins({ weight: "400" });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
