import './globals.css'
import { Providers } from './GlobalRedux/provider'
import { Inter } from 'next/font/google'
import Background from '@/components/Background'

const inter = Inter({ subsets: ['latin'] })
// const poppins = Poppins({ weight: "400" });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
          <Providers>
            <div className='w-screen h-screen overflow-hidden flex justify-center items-center'>
            <Background />
            {children}
            </div>
          </Providers> 
      </body>
    </html>
  )
}
